---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: Un hijo tiene muchas madres.
  checked: false
- value: Uno (y quizás varios) hijo/s tiene/n una madre.
  checked: true
- value: Una madre tiene muchos hijos.
  checked: true
- value: Muchas madres tienen un mismo hijo.
  checked: false
name: Madre hay una sola
