---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: Nombre del artista
  checked: false
- value: ID del artista
  checked: true
- value: Integrantes de la banda
  checked: false
- value: Nacionalidad
  checked: false
