---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: Ponemos el nombre del disco en un campo de la canci칩n
  checked: false
- value: Ponemos el id del disco en un campo de la canci칩n
  checked: true
- value: Ponemos el id de la canci칩n en un campo del 치lbum
  checked: false
