---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: ESTA
  checked: true
- value: ESTA NO
  checked: false
